name: "Post to Bluesky - Avalanche Bot"
on:
  schedule:
    - cron: "*/12 0-7,14-23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: notavs.bsky.social
          BSKY_PASSWORD: ${{ secrets.AVSBOT_BSKY_PASSWORD }}
          MASTODON_HANDLE: "@Avalanche@sportsbots.xyz"
          MASTODON_ACCOUNT_ID: "109705346993799063"
          ALTERNATE_CARD_IMAGE: "https://pbs.twimg.com/profile_images/1808188448207261696/HPCczNqa_400x400.png"
